//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShopWebsite.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BinhLuan
    {
        public int MaBL { get; set; }
        public int MaKH { get; set; }
        public int MaDG { get; set; }

        [Required(ErrorMessage = "Không được để trống bình luận")]
        public string LoiBL { get; set; }
        public System.DateTime ThoiGianBL { get; set; }
    
        public virtual DanhGiaSP DanhGiaSP { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
