//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShopWebsite.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_VaiTro
    {
        public int ID { get; set; }
        public int MaVaiTro { get; set; }
        public int MaNV { get; set; }
        public byte TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
